// <auto-generated />
namespace EmployeeDetails.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class employeetablemodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeetablemodified));
        
        string IMigrationMetadata.Id
        {
            get { return "202007141218229_employee-table-modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
